### PR TITLE
Add new channel and resources for welcome team

### PR DESCRIPTION
**Pull request by jaspermayone**

### CODE REVIEW

**Comment by jaspermayone** [comment]
Adds some new resources for the welcome team, as well as configuring #welcome

**Comment by jaspermayone** [comment]
oh dear, what have I done to the yaml

**Review by grymmy — APPROVED** [review]

**Review by grymmy — CHANGES_REQUESTED** [review]
saw 
Screenshot 2024-04-04 at 7 32 02 PM

**Comment by jaspermayone** [comment]
what have i done graham?

**Comment by jaspermayone** [comment]
shall attempt to fix

**Comment by grymmy** [comment]
> shall attempt to fix

ya did it 
Screenshot 2024-04-04 at 7 36 32 PM

**Pull request merged**
