### PR TITLE
Add Arpan to Clubs stuff on Slack

### PR DESCRIPTION
**Pull request by Arpan-206**
Title

### CODE REVIEW

**Comment by jaspermayone** [comment]
Hey @Arpan-206, this is notifies, you are on the root of the config.

**Review by jaspermayone — CHANGES_REQUESTED** [review]
I have channel notifications setup, feel free to add yourself, but I shouldn't be removed. 

This does not set assignments for specific repos, only notifies when new action items are created.

**Comment by Arpan-206** [comment]
I didn't though?

**Comment by jaspermayone** [comment]
CleanShot 2024-04-09 at 22 30 32@2x

**Comment by Arpan-206** [comment]
That was commented, I figured you didn't want notifications for it.

Oh wait, what exactly does # mean in yaml?

**Comment by jaspermayone** [comment]
it was a comment, might not have been on purpose lol

**Comment by Arpan-206** [comment]
I thought it was lol

**Comment by Arpan-206** [comment]
Feel free to make a separate PR to uncomment/add yourself

**Review by jaspermayone — APPROVED** [review]
Fixed on my own.

**Pull request merged**
